const express = require('express');
const app = express();
const port = 3000;

// Import the WASM module (generated by CPM build)
const wasmModule = require('./pkg/hybrid_project.js');

app.get('/', (req, res) => {
  res.send(`
    <h1>Hybrid Project with CPM</h1>
    <p>This project combines JavaScript (Express) and Rust (WASM)</p>
    <button onclick="testWasm()">Test WASM Function</button>
    <div id="result"></div>
    
    <script>
      async function testWasm() {
        const wasm = await wasmModule.default();
        const result = wasm.add(5, 3);
        document.getElementById('result').innerHTML = 
          \`Rust WASM add(5, 3) = \${result}\`;
      }
    </script>
  `);
});

app.listen(port, () => {
  console.log(`Server running at http://localhost:${port}`);
  console.log('This is a hybrid JavaScript + Rust project managed by CPM!');
});
