name: Setup Branch Protection

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/branch-protection.yml'

jobs:
  setup-protection:
    name: Setup Branch Protection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Branch Protection
        uses: actions/github-script@v7
        with:
          script: |
            const { data: branches } = await github.rest.repos.listBranches({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            const mainBranch = branches.find(branch => branch.name === 'main');
            if (!mainBranch) {
              core.setFailed('Main branch not found');
              return;
            }
            
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: [
                  'CI',
                  'Security',
                  'Coverage',
                  'Documentation'
                ]
              },
              enforce_admins: false,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false
              },
              allow_force_pushes: false,
              allow_deletions: false,
              block_creations: false,
              required_conversation_resolution: true
            });
            
            console.log('Branch protection rules updated successfully'); 